(** OCaml interface for the PROJ.4 library *)

(** Projection type *)
type t

(** Error codes (taken from projects.h in the source dist. of PROJ.4) *)
type errcode =
  | PJD_ERR_NO_ARGS
  | PJD_ERR_LAT_OR_LON_EXCEED_LIMIT
  | PJD_ERR_TOLERANCE_CONDITION
  | PJD_ERR_CONIC_LAT_EQUAL
  | PJD_ERR_LAT_LARGER_THAN_90
  | PJD_ERR_LAT1_IS_ZERO
  | PJD_ERR_LAT_TS_LARGER_THAN_90
  | PJD_ERR_CONTROL_POINT_NO_DIST
  | PJD_ERR_NO_ROTATION_PROJ
  | PJD_ERR_W_OR_M_ZERO_OR_LESS
  | PJD_ERR_LSAT_NOT_IN_RANGE
  | PJD_ERR_PATH_NOT_IN_RANGE
  | PJD_ERR_H_LESS_THAN_ZERO
  | PJD_ERR_LAT_1_OR_2_ZERO_OR_90
  | PJD_ERR_LAT_0_OR_ALPHA_EQ_90
  | PJD_ERR_ELLIPSOID_USE_REQUIRED
  | PJD_ERR_INVALID_UTM_ZONE
  | PJD_ERR_FAILED_TO_FIND_PROJ
  | PJD_ERR_INVALID_M_OR_N
  | PJD_ERR_N_OUT_OF_RANGE
  | PJD_ERR_ABS_LAT1_EQ_ABS_LAT2
  | PJD_ERR_LAT_0_HALF_PI_FROM_MEAN
  | PJD_ERR_GEOCENTRIC
  | PJD_ERR_UNKNOWN_PRIME_MERIDIAN
  | PJD_ERR_AXIS
  | PJD_ERR_GRID_AREA
  | PJD_ERR_INVALID_SWEEP_AXIS
  | PJD_ERR_INVALID_SCALE
  | PJD_ERR_NON_CONVERGENT
  | PJD_ERR_MISSING_ARGS
  | PJD_ERR_LAT_0_IS_ZERO
  | UNKNOWN_ERRCODE

exception Proj4_ERR of int

type trans_t = {
  xt : float;
  yt : float;
}

let _ = Callback.register_exception "Proj4_ERR" (Proj4_ERR 0)

external init_plus : string -> t = "ml_pj_init_plus"
external transform : t -> t -> float array -> float array ->
  float array * float array = "ml_pj_transform"
external transform_one : t -> t -> float -> float -> trans_t
  = "ml_pj_transform_one"
external transform_one_tuple : t -> t -> float -> float -> float * float
  = "ml_pj_transform_one_tuple"
external is_latlong : t -> bool = "ml_pj_is_latlong"
external is_geocent : t -> bool = "ml_pj_is_geocent"
external get_def : t -> string = "ml_pj_get_def"
external latlong_from_proj : t -> t = "ml_pj_latlong_from_proj"

let is_valid s =
  try
    ignore (init_plus s);
    true
  with
  | Invalid_argument _ -> false

let errcode_of_int i =
  match i with
  | -1  -> PJD_ERR_NO_ARGS
  | -14 -> PJD_ERR_LAT_OR_LON_EXCEED_LIMIT
  | -20 -> PJD_ERR_TOLERANCE_CONDITION
  | -21 -> PJD_ERR_CONIC_LAT_EQUAL
  | -22 -> PJD_ERR_LAT_LARGER_THAN_90
  | -23 -> PJD_ERR_LAT1_IS_ZERO
  | -24 -> PJD_ERR_LAT_TS_LARGER_THAN_90
  | -25 -> PJD_ERR_CONTROL_POINT_NO_DIST
  | -26 -> PJD_ERR_NO_ROTATION_PROJ
  | -27 -> PJD_ERR_W_OR_M_ZERO_OR_LESS
  | -28 -> PJD_ERR_LSAT_NOT_IN_RANGE
  | -29 -> PJD_ERR_PATH_NOT_IN_RANGE
  | -30 -> PJD_ERR_H_LESS_THAN_ZERO
  | -32 -> PJD_ERR_LAT_1_OR_2_ZERO_OR_90
  | -33 -> PJD_ERR_LAT_0_OR_ALPHA_EQ_90
  | -34 -> PJD_ERR_ELLIPSOID_USE_REQUIRED
  | -35 -> PJD_ERR_INVALID_UTM_ZONE
  | -37 -> PJD_ERR_FAILED_TO_FIND_PROJ
  | -39 -> PJD_ERR_INVALID_M_OR_N
  | -40 -> PJD_ERR_N_OUT_OF_RANGE
  | -42 -> PJD_ERR_ABS_LAT1_EQ_ABS_LAT2
  | -43 -> PJD_ERR_LAT_0_HALF_PI_FROM_MEAN
  | -45 -> PJD_ERR_GEOCENTRIC
  | -46 -> PJD_ERR_UNKNOWN_PRIME_MERIDIAN
  | -47 -> PJD_ERR_AXIS
  | -48 -> PJD_ERR_GRID_AREA
  | -49 -> PJD_ERR_INVALID_SWEEP_AXIS
  | -52 -> PJD_ERR_INVALID_SCALE
  | -53 -> PJD_ERR_NON_CONVERGENT
  | -54 -> PJD_ERR_MISSING_ARGS
  | -55 -> PJD_ERR_LAT_0_IS_ZERO
  | _ ->   UNKNOWN_ERRCODE

let string_of_errcode =
  function
  | PJD_ERR_NO_ARGS -> "PJD_ERR_NO_ARGS"
  | PJD_ERR_LAT_OR_LON_EXCEED_LIMIT -> "PJD_ERR_LAT_OR_LON_EXCEED_LIMIT"
  | PJD_ERR_TOLERANCE_CONDITION -> "PJD_ERR_TOLERANCE_CONDITION"
  | PJD_ERR_CONIC_LAT_EQUAL -> "PJD_ERR_CONIC_LAT_EQUAL"
  | PJD_ERR_LAT_LARGER_THAN_90 -> "PJD_ERR_LAT_LARGER_THAN_90"
  | PJD_ERR_LAT1_IS_ZERO -> "PJD_ERR_LAT1_IS_ZERO"
  | PJD_ERR_LAT_TS_LARGER_THAN_90 -> "PJD_ERR_LAT_TS_LARGER_THAN_90"
  | PJD_ERR_CONTROL_POINT_NO_DIST -> "PJD_ERR_CONTROL_POINT_NO_DIST"
  | PJD_ERR_NO_ROTATION_PROJ -> "PJD_ERR_NO_ROTATION_PROJ"
  | PJD_ERR_W_OR_M_ZERO_OR_LESS -> "PJD_ERR_W_OR_M_ZERO_OR_LESS"
  | PJD_ERR_LSAT_NOT_IN_RANGE -> "PJD_ERR_LSAT_NOT_IN_RANGE"
  | PJD_ERR_PATH_NOT_IN_RANGE -> "PJD_ERR_PATH_NOT_IN_RANGE"
  | PJD_ERR_H_LESS_THAN_ZERO -> "PJD_ERR_H_LESS_THAN_ZERO"
  | PJD_ERR_LAT_1_OR_2_ZERO_OR_90 -> "PJD_ERR_LAT_1_OR_2_ZERO_OR_90"
  | PJD_ERR_LAT_0_OR_ALPHA_EQ_90 -> "PJD_ERR_LAT_0_OR_ALPHA_EQ_90"
  | PJD_ERR_ELLIPSOID_USE_REQUIRED -> "PJD_ERR_ELLIPSOID_USE_REQUIRED"
  | PJD_ERR_INVALID_UTM_ZONE -> "PJD_ERR_INVALID_UTM_ZONE"
  | PJD_ERR_FAILED_TO_FIND_PROJ -> "PJD_ERR_FAILED_TO_FIND_PROJ"
  | PJD_ERR_INVALID_M_OR_N -> "PJD_ERR_INVALID_M_OR_N"
  | PJD_ERR_N_OUT_OF_RANGE -> "PJD_ERR_N_OUT_OF_RANGE"
  | PJD_ERR_ABS_LAT1_EQ_ABS_LAT2 -> "PJD_ERR_ABS_LAT1_EQ_ABS_LAT2"
  | PJD_ERR_LAT_0_HALF_PI_FROM_MEAN -> "PJD_ERR_LAT_0_HALF_PI_FROM_MEAN"
  | PJD_ERR_GEOCENTRIC -> "PJD_ERR_GEOCENTRIC"
  | PJD_ERR_UNKNOWN_PRIME_MERIDIAN -> "PJD_ERR_UNKNOWN_PRIME_MERIDIAN"
  | PJD_ERR_AXIS -> "PJD_ERR_AXIS"
  | PJD_ERR_GRID_AREA -> "PJD_ERR_GRID_AREA"
  | PJD_ERR_INVALID_SWEEP_AXIS -> "PJD_ERR_INVALID_SWEEP_AXIS"
  | PJD_ERR_INVALID_SCALE -> "PJD_ERR_INVALID_SCALE"
  | PJD_ERR_NON_CONVERGENT -> "PJD_ERR_NON_CONVERGENT"
  | PJD_ERR_MISSING_ARGS -> "PJD_ERR_MISSING_ARGS"
  | PJD_ERR_LAT_0_IS_ZERO -> "PJD_ERR_LAT_0_IS_ZERO"
  | UNKNOWN_ERRCODE -> "UNKNOWN_ERRCODE"
  
